### ISSUE TITLE
Implement an emulator for the multipoles of the 2PCF

### ISSUE THREAD

**Issue by axellapel** [maho3/ltu-ili#39]
We need a fast non-linear summary emulator from the Quijote suite of simulations to build benchmark comparisons for ILI techniques against standard MCMC analyses. We will at first emulate the monopole and quadrupole of the 2pt correlation function with fixed binning and redshift.

_Notes:_ 
- A multi-layer perception should do well enough for such a smooth function.
- We may want to emulate the standard r^2*TPCF to best capture the BAO peak.

EDIT: The first comment is misleading, the emulator aims at quickly estimating the summary for a given cosmology (mean value of the Gaussian likelihood) but not the covariance matrix.

**Comment by modichirag** [comment]
Question/clarification- 
Are you thinking of making an emulator as function of cosmology over Quijote simulations?
To my understanding, standard MCMC analysis estimates covariance matrix at a fixed cosmology to also capture the cosmic variance due to different initial conditions, and afaik there is no cosmology dependence, is there?

**Comment by axellapel** [comment]
No no sure, sorry for the confusion, the comment is misleading. The multi-cosmology emulator is for a fast estimation of the mean in the standard Gaussian likelihood but won't indeed play a role in the estimation of the covariance matrix.

**Comment by axellapel** [comment]
Sure, we can reopen one whenever we need!
